language: php

addons:
  postgresql: "9.5"

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - MOODLE_BRANCH=master
    - MOODLE_BRANCH=MOODLE_37_STABLE
    - MOODLE_BRANCH=MOODLE_38_STABLE
    - MOODLE_BRANCH=MOODLE_39_STABLE
    - MOODLE_BRANCH=MOODLE_310_STABLE
  matrix:
    - DB=pgsql
    - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd || true # Output warnings but do not fail the build because of duplicated but well working code
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc || true # fix later
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
