#!/usr/bin/php
<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * This is an executable PHP script which may help simplify
 * setting up NRPE.
 *
 * Rather than having to configure the php path and settings in the NRPE config,
 * they can be changed in the first line of this file, and check_moodle called
 * as a shell script.
 *
 * It may also be a good idea to move this script outside your web root, and
 * edit the path below.
 *
 * Remember to use "chmod +x" to make it executable!
 *
 * @package    local_nagios
 * @copyright  2014 University of Strathclyde
 * @author     Michael Aherne
 * @author     2020 Adrian Perez, Fernfachhochschule Schweiz (FFHS) <adrian.perez@ffhs.ch>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$MOODLE_DIR = __DIR__.'/../../..';
include $MOODLE_DIR.'/local/nagios/cli/check.php';